name: Deploy Angular PortfolioWeb

# Trigger automatico ad ogni push su main e possibilità di esecuzione manuale
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Clona il repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # 3️⃣ Build Angular
      - name: Build Angular for production
        run: |
          cd portfolioWeb
          npm install
          npm run build -- --project=portfolioWeb --configuration=production --base-href=/newWebPortfolio/

      # 4️⃣ Deploy su GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # Usa il token automatico
          publish_dir: ./portfolioWeb/dist/portfolio-web  # Contiene direttamente index.html e tutti i file
          force_orphan: true  # Ricrea la branch gh-pages da zero
