name: Deploy Angular PortfolioWeb

# Quando far partire il workflow
on:
  push:
    branches:
      - main   # Trigger automatico ad ogni push sulla branch 'main'
  workflow_dispatch:  # Permette di eseguire manualmente il workflow

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Clona il repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # 3️⃣ Build Angular
      - name: Build Angular for production
        run: |
          cd portfolioWeb
          npm install
          npm run build -- --project=portfolioWeb --configuration=production --base-href=/newWebPortfolio/

      # 4️⃣ Deploy su GitHub Pages (forza la branch gh-pages)
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # Usa il token automatico con permessi Read & Write
          publish_dir: ./portfolioWeb/dist/portfolio-web
          force_orphan: true  # Ricrea la branch gh-pages da zero
